import type { NodeImpl, WebNodeSchema } from './types'
import rawSchemas from './schemas.json'

import { inputImage, inputMovie, inputSolidColor, inputWebcam } from './nodes/input'
import { cvColorspace, featClahe, filterBlur, filterCanny, filterGray, filterThreshold, pluginBrightnessContrast, pluginInvert, pluginSobel } from './nodes/image'
import { cvAdaptiveThreshold, cvGamma, cvLevels, cvShadowHighlight, cvWhiteBalance } from './nodes/cvColor'
import { cvDirectionalDilate, cvKmeansSegmentation, cvLbp, cvSkeletonize, cvSsim } from './nodes/cvAdvanced'
import {
  filterGabor,
  filterGlitch,
  filterHighPass,
  filterImgClamp,
  filterLaplacian,
  filterLowPass,
  filterNoiseGaussian,
  filterNoiseSaltPepper,
  filterNoiseSpeckle,
  pluginBlendModes,
  pluginChannelMerge,
  pluginChannelSplit,
  pluginGradient,
  pluginPixelate,
} from './nodes/imageFx'
import {
  featBilateral,
  featContourProps,
  featFillContours,
  featFilterContours,
  featFindContours,
  featHoughCircles,
  featHoughLines,
} from './nodes/features'
import {
  featConnectedComponents,
  featDistanceTransform,
  featMarkerFilter,
  featMorphologyAdv,
  featThresholdAdv,
  featWatershed,
  sciConnectedComponents,
} from './nodes/segmentation'
import { fillHoles, filterFloatThreshold, maskCircle, maskOperations, maskPointQuery, maskToImage } from './nodes/mask'
import {
  drawArrow,
  drawEllipse,
  drawLine,
  drawOverlay,
  drawPoint,
  drawRect,
  drawText,
  drawTintMask,
} from './nodes/draw'
import {
  cvUndistort,
  geomCropRect,
  geomCropper,
  geomObb,
  pluginOffset,
  pluginRotate,
  removeVignette,
  utilRoiPolygon,
} from './nodes/geometry'
import { imageMoments, sciAnalysisReport, sciCalibration, sciInteractiveCalibration, sciMarkerFilter, sciRegionProps } from './nodes/measure'
import { sciBoundaryF1, sciClusterHeatmap, sciGlcm, sciHausdorff, sciRegionClassifier, sciRobustBbox } from './nodes/sciAdvanced'
import { genCanvas, genFeedback, genGrayScott } from './nodes/gen'
import { pluginEvmColor, pluginEvmMotion } from './nodes/evm'
import { sciMEstimator, sciMadScale, sciRobustLocation, sciScalarList } from './nodes/robust1d'
import {
  featSeedsFromBoundaries,
  filterDirectionalMorphology,
  filterLinearDirection,
  filterLinearity,
  maskRegionSealer,
  sciGeneralSegmenter,
} from './nodes/segUtils'
import {
  sciChannelExpr,
  sciColorDistance,
  sciColormap,
  sciDeltaE,
  sciFirstOrderStats,
  sciFocusMetric,
  sciFrameAccumulator,
  sciHistCompare,
  sciHistogram,
  sciLineProfile,
  sciMaskMetrics,
  sciMatrixDist,
  sciNoiseEstimate,
  sciNormalizer,
  sciRangeChecker,
  sciRegionColorStats,
  sciRoiStats,
  sciScaleBar,
} from './nodes/sci'
import { forensicFootprint } from './nodes/analysis'
import { analysisFaceMp, analysisHandMp, analysisObjectMp, analysisPoseMp, geomTrackPoint } from './nodes/body'
import {
  dataCoordCombine,
  dataCoordSplitter,
  dataGroupDicts,
  dataListOps,
  dataListSelector,
  dictBuilder,
  listRegionSelect,
  mathAbs,
  mathAdd,
  mathClamp,
  mathCos,
  mathDistance,
  mathDiv,
  mathMax,
  mathMin,
  mathMod,
  mathMul,
  mathPow,
  mathRound,
  mathSin,
  mathSub,
  pluginDictGet,
  scalarInput,
  utilDictMerge,
  utilLandmarkSelector,
} from './nodes/dataMath'
import {
  canvasFrame,
  canvasNote,
  logicCollect,
  logicCompare,
  logicGateNode,
  logicLatch,
  logicPresence,
  logicPython,
  logicSwitch,
  mathExpr,
  mathMapRange,
  mathOperation,
  signalGate,
  stringCase,
  stringConcat,
  stringInput,
  stringLength,
  stringReplace,
  stringSplit,
  utilFilterLabel,
} from './nodes/logic'
import {
  pluginFilterEma,
  pluginFilterGaussian,
  pluginFilterHolt,
  pluginFilterKalman,
  pluginFilterLoess,
  pluginFilterLowpass,
  pluginFilterMa,
  pluginFilterMedian,
  pluginFilterParticle,
  pluginFilterSavgol,
} from './nodes/signal'
import { dataInspector, outputDisplay, utilCsvExport } from './nodes/output'
import { geoGrainHistogram, plotterPro } from './nodes/visualize'

export const SCHEMAS = rawSchemas as unknown as WebNodeSchema[]

export const IMPLEMENTATIONS: Record<string, NodeImpl> = {
  canvas_note: canvasNote,
  canvas_frame: canvasFrame,

  input_image: inputImage,
  input_movie: inputMovie,
  input_webcam: inputWebcam,
  input_solid_color: inputSolidColor,

  filter_gray: filterGray,
  filter_blur: filterBlur,
  filter_canny: filterCanny,
  filter_threshold: filterThreshold,
  plugin_invert: pluginInvert,
  plugin_brightness_contrast: pluginBrightnessContrast,
  plugin_sobel: pluginSobel,
  cv_colorspace: cvColorspace,
  feat_clahe: featClahe,
  cv_gamma: cvGamma,
  cv_levels: cvLevels,
  cv_shadow_highlight: cvShadowHighlight,
  cv_adaptive_threshold: cvAdaptiveThreshold,
  cv_white_balance: cvWhiteBalance,
  feat_bilateral: featBilateral,
  filter_noise_gaussian: filterNoiseGaussian,
  filter_noise_salt_pepper: filterNoiseSaltPepper,
  filter_noise_speckle: filterNoiseSpeckle,
  filter_gabor: filterGabor,
  filter_high_pass: filterHighPass,
  filter_low_pass: filterLowPass,
  filter_laplacian: filterLaplacian,
  filter_img_clamp: filterImgClamp,
  plugin_gradient: pluginGradient,
  plugin_channel_split: pluginChannelSplit,
  plugin_channel_merge: pluginChannelMerge,
  plugin_blend_modes: pluginBlendModes,
  plugin_pixelate: pluginPixelate,
  filter_glitch: filterGlitch,

  feat_threshold_adv: featThresholdAdv,
  feat_morphology_adv: featMorphologyAdv,
  feat_distance_transform: featDistanceTransform,
  feat_connected_components: featConnectedComponents,
  sci_connected_components: sciConnectedComponents,
  feat_marker_filter: featMarkerFilter,
  feat_watershed: featWatershed,
  feat_find_contours: featFindContours,
  feat_contour_props: featContourProps,
  feat_filter_contours: featFilterContours,
  feat_fill_contours: featFillContours,
  feat_hough_circles: featHoughCircles,
  feat_hough_lines: featHoughLines,
  cv_kmeans_segmentation: cvKmeansSegmentation,

  cv_lbp: cvLbp,
  cv_ssim: cvSsim,

  fill_holes: fillHoles,
  mask_operations: maskOperations,
  mask_circle: maskCircle,
  mask_point_query: maskPointQuery,
  plugin_mask_to_image: maskToImage,
  cv_skeletonize: cvSkeletonize,
  cv_directional_dilate: cvDirectionalDilate,
  filter_float_threshold: filterFloatThreshold,

  draw_arrow: drawArrow,
  draw_ellipse: drawEllipse,
  draw_line: drawLine,
  draw_point: drawPoint,
  draw_rect: drawRect,
  draw_text: drawText,
  draw_overlay: drawOverlay,
  draw_tint_mask: drawTintMask,

  util_roi_polygon: utilRoiPolygon,
  geom_obb: geomObb,
  cv_undistort: cvUndistort,
  plugin_rotate: pluginRotate,
  plugin_offset: pluginOffset,
  geom_crop_rect: geomCropRect,
  geom_cropper: geomCropper,
  remove_vignette: removeVignette,

  sci_marker_filter: sciMarkerFilter,
  sci_region_props: sciRegionProps,
  sci_interactive_calibration: sciInteractiveCalibration,
  sci_calibration: sciCalibration,
  image_moments: imageMoments,
  sci_analysis_report: sciAnalysisReport,
  sci_first_order_stats: sciFirstOrderStats,
  sci_normalizer: sciNormalizer,
  sci_roi_stats: sciRoiStats,
  sci_color_distance: sciColorDistance,
  sci_delta_e: sciDeltaE,
  sci_channel_expr: sciChannelExpr,
  sci_histogram: sciHistogram,
  sci_hist_compare: sciHistCompare,
  sci_mask_metrics: sciMaskMetrics,
  sci_line_profile: sciLineProfile,
  sci_scale_bar: sciScaleBar,
  sci_focus_metric: sciFocusMetric,
  sci_noise_estimate: sciNoiseEstimate,
  sci_matrix_dist: sciMatrixDist,
  sci_colormap: sciColormap,
  sci_range_checker: sciRangeChecker,
  sci_region_color_stats: sciRegionColorStats,
  sci_frame_accumulator: sciFrameAccumulator,
  sci_glcm: sciGlcm,
  sci_hausdorff: sciHausdorff,
  sci_boundary_f1: sciBoundaryF1,
  sci_robust_bbox: sciRobustBbox,
  sci_region_classifier: sciRegionClassifier,
  sci_cluster_heatmap: sciClusterHeatmap,
  sci_scalar_list: sciScalarList,
  sci_robust_location: sciRobustLocation,
  sci_mad_scale: sciMadScale,
  sci_m_estimator: sciMEstimator,
  feat_seeds_from_boundaries: featSeedsFromBoundaries,
  sci_general_segmenter: sciGeneralSegmenter,
  filter_linearity: filterLinearity,
  mask_region_sealer: maskRegionSealer,
  filter_linear_direction: filterLinearDirection,
  filter_directional_morphology: filterDirectionalMorphology,

  gen_canvas: genCanvas,
  gen_feedback: genFeedback,
  gen_gray_scott: genGrayScott,
  plugin_evm_color: pluginEvmColor,
  plugin_evm_motion: pluginEvmMotion,

  geo_grain_histogram: geoGrainHistogram,
  forensic_footprint: forensicFootprint,

  analysis_face_mp: analysisFaceMp,
  analysis_hand_mp: analysisHandMp,
  analysis_pose_mp: analysisPoseMp,
  analysis_object_mp: analysisObjectMp,
  geom_track_point: geomTrackPoint,

  data_coord_combine: dataCoordCombine,
  data_coord_splitter: dataCoordSplitter,
  data_list_selector: dataListSelector,
  plugin_dict_get: pluginDictGet,
  list_region_select: listRegionSelect,
  data_list_ops: dataListOps,
  util_landmark_selector: utilLandmarkSelector,
  util_dict_merge: utilDictMerge,
  data_group_dicts: dataGroupDicts,
  dict_builder: dictBuilder,

  math_add: mathAdd,
  math_sub: mathSub,
  math_mul: mathMul,
  math_div: mathDiv,
  math_mod: mathMod,
  math_min: mathMin,
  math_max: mathMax,
  math_pow: mathPow,
  math_abs: mathAbs,
  math_round: mathRound,
  math_sin: mathSin,
  math_cos: mathCos,
  math_clamp: mathClamp,
  math_distance: mathDistance,
  scalar_input: scalarInput,

  plugin_filter_ma: pluginFilterMa,
  plugin_filter_ema: pluginFilterEma,
  plugin_filter_kalman: pluginFilterKalman,
  plugin_filter_median: pluginFilterMedian,
  plugin_filter_savgol: pluginFilterSavgol,
  plugin_filter_lowpass: pluginFilterLowpass,
  plugin_filter_holt: pluginFilterHolt,
  plugin_filter_gaussian: pluginFilterGaussian,
  plugin_filter_loess: pluginFilterLoess,
  plugin_filter_particle: pluginFilterParticle,

  logic_python: logicPython,
  logic_collect: logicCollect,
  signal_gate: signalGate,
  logic_latch: logicLatch,
  logic_compare: logicCompare,
  logic_presence: logicPresence,
  logic_switch: logicSwitch,
  logic_gate: logicGateNode,
  util_filter_label: utilFilterLabel,

  string_concat: stringConcat,
  string_split: stringSplit,
  string_length: stringLength,
  string_case: stringCase,
  string_replace: stringReplace,
  string_input: stringInput,

  math_expr: mathExpr,
  math_map_range: mathMapRange,
  math_operation: mathOperation,

  plotter_pro: plotterPro,
  data_inspector: dataInspector,
  output_display: outputDisplay,
  util_csv_export: utilCsvExport,
}

const schemaByType = new Map(SCHEMAS.map((s) => [s.type, s]))

export function getSchema(type: string): WebNodeSchema | undefined {
  return schemaByType.get(type)
}
